version: '3.4'
services:
  app:
    build:
      context: .
      target: development
    command: "ruby run.rb"
    volumes:
      - ".:/app"
    environment:
      FEED_ID: "gsdsdfgsdfgsdfgsdfgsdfgsdf"
      SLEEP_TIME: 10
      MQTT_URI: 'broker'
      MQTT_TOPIC: 'XXXXX'
  broker:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
